version: '3'

services:
  ansible-vmware-pwsh:
    build:
      ./ansible-vmware
    volumes:
      - ./my-playbooks:/home/ansible/Automation
      - ~/.ssh:/home/ansible/.ssh
      - ~/.gitconfig:/home/ansible/.gitconfig
    stdin_open: true
    tty: true
    command: tail -f /dev/null

